@base_url = http://localhost:3000
Content-Type: application/json

{
    "identity":"bentesssssadt123@gmail.com",
    "username":"Kodlsdxsasadd444",
    "password":"testpass1234",
    "confirmPassword":"testpass1234",
    "firstName":"nasdasd",
    "lastName":"asdasdasd",
    "dateOfBirth":"23/01/2545"
}

### POST Login  เข้าใช้งาน Website
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    "username":"Kodlsdxsasadd444",
    "password":"testpass1234"
}

### GET me ดูข้อมูลของ User
GET {{base_url}}/api/users/me
Authorization: Bearer {{token}}


### PATCH me อัพเดทข้อมูล User
PATCH {{base_url}}/api/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "identity":"0123sasda"
}


### POST Initial Reading เริ่ม Session
POST {{base_url}}/api/readings/init
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "spreadId":1,
    "isDaily":true,
    "question":"ไดรnaฟ์จะทำงานเสร็จ",
    "allowReversed":true
}

### POST Shuffle Card 
POST {{base_url}}/api/readings/shuffle
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "readingId":36,
    "times":23,
    "allowReversed":true
}

### POST Cut Card
POST {{base_url}}/api/readings/cut
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "readingId":36,
    "position":7
}


### POST Pick Card
POST {{base_url}}/api/readings/pick
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "readingId":36,
    "selectId":[
         {"id":1,"isReversed": false},
         {"id":3,"isReversed": true},
         {"id":5,"isReversed": true}
        ]
}

### POST AI Interpret
POST {{base_url}}/api/readings/ai-interpret
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "readingId":36,
    "spreadType": "TarotOfTheDay",
  "question": "ไดรฟ์จะทำงานเสร็จ",
  "card": [
    {
      "id": 1,
      "name": "The Fool",
      "upright_Mean": "การเริ่มต้นใหม่, อิสระ, ความไร้เดียงสา",
      "reverse_Mean": "ความประมาท, การตัดสินใจผิดพลาด",
      "img_url": "https://upload.wikimedia.org/wikipedia/en/9/90/RWS_Tarot_00_Fool.jpg",
      "cardNumber": 0,
      "type": "MAJOR"
    },
    {
      "id": 3,
      "name": "The High Priestess",
      "upright_Mean": "สัญชาตญาณ, ความลึกลับ, ความรู้ภายใน",
      "reverse_Mean": "ความสับสน, การมองข้ามสัญชาตญาณ",
      "img_url": "https://upload.wikimedia.org/wikipedia/en/8/88/RWS_Tarot_02_High_Priestess.jpg",
      "cardNumber": 2,
      "type": "MAJOR"
    },
    {
      "id": 5,
      "name": "The Emperor",
      "upright_Mean": "อำนาจ, โครงสร้าง, การปกป้อง",
      "reverse_Mean": "การเผด็จการ, ความเข้มงวดเกินไป",
      "img_url": "https://upload.wikimedia.org/wikipedia/en/c/c3/RWS_Tarot_04_Emperor.jpg",
      "cardNumber": 4,
      "type": "MAJOR"
    }
  ]
}

### GET ให้ข้อมูลแสดงว่าจะแชร์ออกไปใน Social
GET {{base_url}}/api/readings/share-image/36
Authorization: Bearer {{token}}

### GET Spread ทั้งหมด
GET {{base_url}}/api/readings/spread
Authorization: Bearer {{token}}


### GET Spread ที่ต้องการ
GET {{base_url}}/api/readings/spread/1
Authorization: Bearer {{token}}



### GET ประวัติการดูดวง
GET {{base_url}}/api/users/history
Authorization: Bearer {{token}}


### POST บันทึกประวัติดูดวง
POST {{base_url}}/api/users/saved-readings
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "readingId":64,
  "note":"today is so bad"
}

### GET ดึงประวัติการบันทึกดูดวง
GET {{base_url}}/api/users/saved-readings
Authorization: Bearer {{token}}

### GET ดึงประวัติการบันทึกดูดวงรายอัน
GET {{base_url}}/api/users/saved-readings/64
Authorization: Bearer {{token}}

### DELETE ยกเลิกบันทึกประวัติดูดวง
DELETE {{base_url}}/api/users/saved-readings/64
Authorization: Bearer {{token}}




### GET ดูข้อมูลการ์ดทั้งหมดที่อยู่ในระบบ
GET {{base_url}}/api/cards
Authorization: Bearer {{token}}

### GET ดูข้อมูลการ์ดแต่ละใบ
GET {{base_url}}/api/cards/1
Authorization: Bearer {{token}}