const SACRED_BASE_URL = "https://www.sacred-texts.com/tarot/pkt/img/";

export const cardData = [
  // --- MAJOR ARCANA (0 - 21) ---
  { cardNumber: 0, name: "The Fool", type: "MAJOR", upright_Mean: "การเริ่มต้นใหม่, อิสระ, ความไร้เดียงสา", reverse_Mean: "ความประมาท, การตัดสินใจผิดพลาด, ความโته", img_url: `${SACRED_BASE_URL}ar00.jpg` },
  { cardNumber: 1, name: "The Magician", type: "MAJOR", upright_Mean: "ทักษะ, ความสามารถ, การลงมือทำ", reverse_Mean: "การหลอกลวง, ความลังเล, การใช้ความสามารถในทางที่ผิด", img_url: `${SACRED_BASE_URL}ar01.jpg` },
  { cardNumber: 2, name: "The High Priestess", type: "MAJOR", upright_Mean: "สัญชาตญาณ, ความลึกลับ, ความรู้ภายใน", reverse_Mean: "ความสับสน, การมองข้ามสัญชาตญาณ, ความลับถูกเปิดเผย", img_url: `${SACRED_BASE_URL}ar02.jpg` },
  { cardNumber: 3, name: "The Empress", type: "MAJOR", upright_Mean: "ความอุดมสมบูรณ์, ธรรมชาติ, ความเป็นแม่", reverse_Mean: "ความพึ่งพาคนอื่นมากเกินไป, ความคิดสร้างสรรค์หยุดชะงัก", img_url: `${SACRED_BASE_URL}ar03.jpg` },
  { cardNumber: 4, name: "The Emperor", type: "MAJOR", upright_Mean: "อำนาจ, โครงสร้าง, การปกป้อง", reverse_Mean: "การเผด็จการ, ความเข้มงวดเกินไป, ขาดการควบคุม", img_url: `${SACRED_BASE_URL}ar04.jpg` },
  { cardNumber: 5, name: "The Hierophant", type: "MAJOR", upright_Mean: "ประเพณี, ความเชื่อ, การศึกษา", reverse_Mean: "การขบถ, ความเชื่อที่ฝังหัว, การทำนอกกรอบ", img_url: `${SACRED_BASE_URL}ar05.jpg` },
  { cardNumber: 6, name: "The Lovers", type: "MAJOR", upright_Mean: "ความรัก, ความสัมพันธ์, การเลือก", reverse_Mean: "ความไม่สมดุล, ความขัดแย้งในใจ, การเลิกรา", img_url: `${SACRED_BASE_URL}ar06.jpg` },
  { cardNumber: 7, name: "The Chariot", type: "MAJOR", upright_Mean: "ชัยชนะ, ความมุ่งมั่น, การควบคุม", reverse_Mean: "การขาดทิศทาง, ความก้าวร้าว, การสูญเสียการควบคุม", img_url: `${SACRED_BASE_URL}ar07.jpg` },
  { cardNumber: 8, name: "Strength", type: "MAJOR", upright_Mean: "ความกล้าหาญ, ความเมตตา, พลังภายใน", reverse_Mean: "ความอ่อนแอ, การขาดการควบคุมอารมณ์, ความมั่นใจต่ำ", img_url: `${SACRED_BASE_URL}ar08.jpg` },
  { cardNumber: 9, name: "The Hermit", type: "MAJOR", upright_Mean: "การวิเวก, การค้นหาตัวเอง, คำแนะนำ", reverse_Mean: "ความโดดเดี่ยว, การตัดขาดจากโลก, ความสันโดษที่มากเกินไป", img_url: `${SACRED_BASE_URL}ar09.jpg` },
  { cardNumber: 10, name: "Wheel of Fortune", type: "MAJOR", upright_Mean: "โชคชะตา, จุดเปลี่ยน, วัฏจักร", reverse_Mean: "โชคร้าย, การต่อต้านการเปลี่ยนแปลง, อุปสรรคที่ไม่คาดคิด", img_url: `${SACRED_BASE_URL}ar10.jpg` },
  { cardNumber: 11, name: "Justice", type: "MAJOR", upright_Mean: "ความยุติธรรม, ความจริง, กฎแห่งกรรม", reverse_Mean: "ความอยุติธรรม, การไม่ยอมรับความจริง, การตัดสินใจที่ลำเอียง", img_url: `${SACRED_BASE_URL}ar11.jpg` },
  { cardNumber: 12, name: "The Hanged Man", type: "MAJOR", upright_Mean: "การเสียสละ, มุมมองใหม่, การรอคอย", reverse_Mean: "ความล่าช้าที่ไม่เกิดประโยชน์, การดื้อรั้น, การติดขัด", img_url: `${SACRED_BASE_URL}ar12.jpg` },
  { cardNumber: 13, name: "Death", type: "MAJOR", upright_Mean: "การสิ้นสุดเพื่อเริ่มต้นใหม่, การเปลี่ยนแปลง", reverse_Mean: "การกลัวการเปลี่ยนแปลง, การยึดติด, การยื้อเวลา", img_url: `${SACRED_BASE_URL}ar13.jpg` },
  { cardNumber: 14, name: "Temperance", type: "MAJOR", upright_Mean: "ความสมดุล, การปรับตัว, ความอดทน", reverse_Mean: "ความไม่พอดี, ความขัดแย้ง, การขาดความสมดุล", img_url: `${SACRED_BASE_URL}ar14.jpg` },
  { cardNumber: 15, name: "The Devil", type: "MAJOR", upright_Mean: "กิเลส, การยึดติด, อบายมุข", reverse_Mean: "การหลุดพ้น, การตระหนักรู้, การเป็นอิสระจากพันธนาการ", img_url: `${SACRED_BASE_URL}ar15.jpg` },
  { cardNumber: 16, name: "The Tower", type: "MAJOR", upright_Mean: "การพังทลายอย่างกะทันหัน, วิกฤต", reverse_Mean: "การหลีกเลี่ยงภัยพิบัติ, การชะลอความสูญเสีย, การเริ่มใหม่ช้าๆ", img_url: `${SACRED_BASE_URL}ar16.jpg` },
  { cardNumber: 17, name: "The Star", type: "MAJOR", upright_Mean: "ความหวัง, แรงบันดาลใจ, การเยียวยา", reverse_Mean: "ความสิ้นหวัง, การขาดแรงจูงใจ, ความผิดหวัง", img_url: `${SACRED_BASE_URL}ar17.jpg` },
  { cardNumber: 18, name: "The Moon", type: "MAJOR", upright_Mean: "ความวิตกกังวล, ภาพลวงตา, สัญชาตญาณ", reverse_Mean: "ความจริงเปิดเผย, การเอาชนะความกลัว, ความสับสนเริ่มจางไป", img_url: `${SACRED_BASE_URL}ar18.jpg` },
  { cardNumber: 19, name: "The Sun", type: "MAJOR", upright_Mean: "ความสำเร็จ, ความสุข, พลังงานบวก", reverse_Mean: "ความผิดหวังชั่วคราว, ความสำเร็จที่ล่าช้า, ความเศร้าหมอง", img_url: `${SACRED_BASE_URL}ar19.jpg` },
  { cardNumber: 20, name: "Judgement", type: "MAJOR", upright_Mean: "การตื่นรู้, การตัดสินใจครั้งสำคัญ", reverse_Mean: "การตำหนิตัวเอง, การลังเล, พลาดโอกาสสำคัญ", img_url: `${SACRED_BASE_URL}ar20.jpg` },
  { cardNumber: 21, name: "The World", type: "MAJOR", upright_Mean: "ความสมบูรณ์แบบ, ความสำเร็จ, การเดินทาง", reverse_Mean: "งานที่ยังไม่เสร็จ, ความล่าช้า, การขาดความพยายาม", img_url: `${SACRED_BASE_URL}ar21.jpg` },

  // --- WANDS ---
  { cardNumber: 22, name: "Ace of Wands", type: "MINOR", upright_Mean: "แรงบันดาลใจใหม่, โอกาสสร้างสรรค์", reverse_Mean: "ความล่าช้า, ขาดพลังงาน, เป้าหมายไม่ชัดเจน", img_url: `${SACRED_BASE_URL}waac.jpg` },
  { cardNumber: 23, name: "Two of Wands", type: "MINOR", upright_Mean: "การวางแผน, การตัดสินใจมองไกล", reverse_Mean: "ความกลัวความเสี่ยง, การวางแผนผิดพลาด", img_url: `${SACRED_BASE_URL}wa02.jpg` },
  { cardNumber: 24, name: "Three of Wands", type: "MINOR", upright_Mean: "การขยายตัว, การรอคอยผลลัพธ์ที่คุ้มค่า", reverse_Mean: "ความผิดพลาดทางการวางแผน, ความล้มเหลวในการขยายงาน", img_url: `${SACRED_BASE_URL}wa03.jpg` },
  { cardNumber: 25, name: "Four of Wands", type: "MINOR", upright_Mean: "การเฉลิมฉลอง, ความสุขในบ้าน, ความมั่นคง", reverse_Mean: "ความไม่สงบในครอบครัว, ชัยชนะที่จืดจาง", img_url: `${SACRED_BASE_URL}wa04.jpg` },
  { cardNumber: 26, name: "Five of Wands", type: "MINOR", upright_Mean: "ความขัดแย้ง, การแข่งขัน, การต่อสู้ทางความคิด", reverse_Mean: "ความเข้าใจผิดที่จบลง, การหลีกเลี่ยงความขัดแย้ง", img_url: `${SACRED_BASE_URL}wa05.jpg` },
  { cardNumber: 27, name: "Six of Wands", type: "MINOR", upright_Mean: "ชัยชนะ, การยอมรับ, ข่าวดี", reverse_Mean: "ความพ่ายแพ้, การเสียความมั่นใจ, ชื่อเสียงเสียหาย", img_url: `${SACRED_BASE_URL}wa06.jpg` },
  { cardNumber: 28, name: "Seven of Wands", type: "MINOR", upright_Mean: "การปกป้องสิทธิ์, การยืนหยัดสู้", reverse_Mean: "การยอมแพ้, ความเหนื่อยล้าเกินรับไหว", img_url: `${SACRED_BASE_URL}wa07.jpg` },
  { cardNumber: 29, name: "Eight of Wands", type: "MINOR", upright_Mean: "ความรวดเร็ว, ข่าวดีมาไว, การสื่อสาร", reverse_Mean: "ความล่าช้า, ความโกลาหล, ข่าวร้าย", img_url: `${SACRED_BASE_URL}wa08.jpg` },
  { cardNumber: 30, name: "Nine of Wands", type: "MINOR", upright_Mean: "ความอดทน, การเตรียมพร้อมรับมือ", reverse_Mean: "ความท้อแท้, กำแพงใจสูงเกินไป, การถอดใจ", img_url: `${SACRED_BASE_URL}wa09.jpg` },
  { cardNumber: 31, name: "Ten of Wands", type: "MINOR", upright_Mean: "ภาระหนัก, ความรับผิดชอบมากเกินไป", reverse_Mean: "การปล่อยวางภาระ, ความพยายามที่สูญเปล่า", img_url: `${SACRED_BASE_URL}wa10.jpg` },
  { cardNumber: 32, name: "Page of Wands", type: "MINOR", upright_Mean: "การสำรวจ, ข่าวสารใหม่, แรงไฟวัยเยาว์", reverse_Mean: "ความคิดเพ้อฝัน, ข่าวร้าย, ความใจร้อน", img_url: `${SACRED_BASE_URL}wapa.jpg` },
  { cardNumber: 33, name: "Knight of Wands", type: "MINOR", upright_Mean: "ความมุ่งมั่น, ความมุทะลุ, การเดินทาง", reverse_Mean: "ความหุนหันพลันแล่น, การหยุดชะงักกะทันหัน", img_url: `${SACRED_BASE_URL}wakn.jpg` },
  { cardNumber: 34, name: "Queen of Wands", type: "MINOR", upright_Mean: "ความมั่นใจ, พลังดึงดูด, ความอบอุ่น", reverse_Mean: "ความอิจฉา, ความเห็นแก่ตัว, อารมณ์แปรปรวน", img_url: `${SACRED_BASE_URL}waqu.jpg` },
  { cardNumber: 35, name: "King of Wands", type: "MINOR", upright_Mean: "ความเป็นผู้นำ, วิสัยทัศน์กว้างไกล", reverse_Mean: "ความเผด็จการ, ความประมาท, อีโก้สูง", img_url: `${SACRED_BASE_URL}waki.jpg` },

  // --- CUPS ---
  { cardNumber: 36, name: "Ace of Cups", type: "MINOR", upright_Mean: "ความรักใหม่, ความรู้สึกเต็มเปี่ยม, ความสุข", reverse_Mean: "ความเสียใจ, ปิดกั้นทางอารมณ์, รักที่ไม่สมหวัง", img_url: `${SACRED_BASE_URL}cuac.jpg` },
  { cardNumber: 37, name: "Two of Cups", type: "MINOR", upright_Mean: "ความสัมพันธ์ที่ดี, คู่ครอง, มิตรภาพ", reverse_Mean: "ความแตกแยก, ไม่ลงรอย, การทะเลาะเบาะแว้ง", img_url: `${SACRED_BASE_URL}cu02.jpg` },
  { cardNumber: 38, name: "Three of Cups", type: "MINOR", upright_Mean: "มิตรภาพ, การเฉลิมฉลอง, สังคมที่ดี", reverse_Mean: "ความสนุกที่เกินขอบเขต, มือที่สาม, การถูกละเลย", img_url: `${SACRED_BASE_URL}cu03.jpg` },
  { cardNumber: 39, name: "Four of Cups", type: "MINOR", upright_Mean: "ความเบื่อหน่าย, การเมินเฉยต่อโอกาส", reverse_Mean: "การตื่นตัว, เริ่มเห็นโอกาสใหม่ๆ", img_url: `${SACRED_BASE_URL}cu04.jpg` },
  { cardNumber: 40, name: "Five of Cups", type: "MINOR", upright_Mean: "ความสูญเสีย, ความเศร้าเสียใจ", reverse_Mean: "การทำใจได้, การก้าวต่อ, การฟื้นฟูจิตใจ", img_url: `${SACRED_BASE_URL}cu05.jpg` },
  { cardNumber: 41, name: "Six of Cups", type: "MINOR", upright_Mean: "ความคิดถึง, ความสุขในอดีต, การกลับมาพบ", reverse_Mean: "การติดอยู่ในอดีตเกินไป, การก้าวไปสู่อนาคต", img_url: `${SACRED_BASE_URL}cu06.jpg` },
  { cardNumber: 42, name: "Seven of Cups", type: "MINOR", upright_Mean: "ทางเลือกมากมาย, จินตนาการ, ความเพ้อฝัน", reverse_Mean: "ความสับสนเริ่มหายไป, การเห็นความเป็นจริง", img_url: `${SACRED_BASE_URL}cu07.jpg` },
  { cardNumber: 43, name: "Eight of Cups", type: "MINOR", upright_Mean: "การเดินจากไปเพื่อสิ่งที่ดีกว่า", reverse_Mean: "ความกลัวการสูญเสีย, การทนอยู่ในสถานการณ์เดิม", img_url: `${SACRED_BASE_URL}cu08.jpg` },
  { cardNumber: 44, name: "Nine of Cups", type: "MINOR", upright_Mean: "ความสมหวัง, ความพึงพอใจสูงสุด", reverse_Mean: "ความโลภ, ความว่างเปล่าภายใต้เปลือกที่สวยงาม", img_url: `${SACRED_BASE_URL}cu09.jpg` },
  { cardNumber: 45, name: "Ten of Cups", type: "MINOR", upright_Mean: "ความสุขในครอบครัว, ความรักที่ยั่งยืน", reverse_Mean: "ปัญหาในบ้าน, ความขัดแย้งของญาติพี่น้อง", img_url: `${SACRED_BASE_URL}cu10.jpg` },
  { cardNumber: 46, name: "Page of Cups", type: "MINOR", upright_Mean: "ข่าวสารที่น่ายินดี, ความคิดสร้างสรรค์ใหม่", reverse_Mean: "ความเพ้อเจ้อ, อารมณ์แปรปรวน, ข่าวร้ายทางใจ", img_url: `${SACRED_BASE_URL}cupa.jpg` },
  { cardNumber: 47, name: "Knight of Cups", type: "MINOR", upright_Mean: "ความโรแมนติก, ข้อเสนอ, ชายหนุ่มรูปงาม", reverse_Mean: "ความไม่จริงใจ, อารมณ์อ่อนไหวเกินเหตุ", img_url: `${SACRED_BASE_URL}cukn.jpg` },
  { cardNumber: 48, name: "Queen of Cups", type: "MINOR", upright_Mean: "ความเมตตา, สัญชาตญาณแม่นยำ", reverse_Mean: "ความไม่มั่นคงทางอารมณ์, ความช่างมโน", img_url: `${SACRED_BASE_URL}cuqu.jpg` },
  { cardNumber: 49, name: "King of Cups", type: "MINOR", upright_Mean: "การควบคุมอารมณ์, ความเห็นอกเห็นใจ", reverse_Mean: "การชักจูงอารมณ์คนอื่น, ความเย็นชา, ติดสุรา", img_url: `${SACRED_BASE_URL}cuki.jpg` },

  // --- SWORDS ---
  { cardNumber: 50, name: "Ace of Swords", type: "MINOR", upright_Mean: "ความชัดเจน, ชัยชนะทางปัญญา, การตัดสินใจ", reverse_Mean: "ความสับสน, ความรุนแรง, ความผิดพลาดทางความคิด", img_url: `${SACRED_BASE_URL}swac.jpg` },
  { cardNumber: 51, name: "Two of Swords", type: "MINOR", upright_Mean: "การตัดสินใจลำบาก, ทางตัน, การปิดตา", reverse_Mean: "ความวุ่นวาย, การมองเห็นความจริงที่เจ็บปวด", img_url: `${SACRED_BASE_URL}sw02.jpg` },
  { cardNumber: 52, name: "Three of Swords", type: "MINOR", upright_Mean: "ความเสียใจ, ความเจ็บปวด, การหักหลัง", reverse_Mean: "การเยียวยา, เริ่มยอมรับความจริงได้", img_url: `${SACRED_BASE_URL}sw03.jpg` },
  { cardNumber: 53, name: "Four of Swords", type: "MINOR", upright_Mean: "การพักผ่อน, การทำสมาธิ, การหยุดนิ่ง", reverse_Mean: "ความล้าสะสม, การถูกบังคับให้กลับมาสู้", img_url: `${SACRED_BASE_URL}sw04.jpg` },
  { cardNumber: 54, name: "Five of Swords", type: "MINOR", upright_Mean: "ชัยชนะที่ว่างเปล่า, ความขัดแย้ง", reverse_Mean: "ความแค้นที่ฝังลึก, การพยายามยุติปัญหา", img_url: `${SACRED_BASE_URL}sw05.jpg` },
  { cardNumber: 55, name: "Six of Swords", type: "MINOR", upright_Mean: "การผ่านพ้นวิกฤต, การเดินทางหนีปัญหา", reverse_Mean: "การติดหล่มปัญหาเดิมๆ, หนีไม่พ้น", img_url: `${SACRED_BASE_URL}sw06.jpg` },
  { cardNumber: 56, name: "Seven of Swords", type: "MINOR", upright_Mean: "ความลับ, การหลบเลี่ยง, กลอุบาย", reverse_Mean: "ความละอายใจ, การถูกเปิดเผยความลับ", img_url: `${SACRED_BASE_URL}sw07.jpg` },
  { cardNumber: 57, name: "Eight of Swords", type: "MINOR", upright_Mean: "ความอึดอัด, การถูกจำกัด, ความกลัว", reverse_Mean: "ความเป็นอิสระ, การหลุดพ้นจากกรอบเดิม", img_url: `${SACRED_BASE_URL}sw08.jpg` },
  { cardNumber: 58, name: "Nine of Swords", type: "MINOR", upright_Mean: "ความกังวล, การนอนไม่หลับ, ฝันร้าย", reverse_Mean: "การคลายกังวล, การเผชิญหน้าความจริง", img_url: `${SACRED_BASE_URL}sw09.jpg` },
  { cardNumber: 59, name: "Ten of Swords", type: "MINOR", upright_Mean: "จุดต่ำสุด, ความพ่ายแพ้, จบสิ้น", reverse_Mean: "การฟื้นตัวช้าๆ, การเริ่มต้นใหม่หลังพายุ", img_url: `${SACRED_BASE_URL}sw10.jpg` },
  { cardNumber: 60, name: "Page of Swords", type: "MINOR", upright_Mean: "ความตื่นตัว, การสอดแนม, ความอยากรู้", reverse_Mean: "ดีแต่พูด, ความใจร้อน, การนินทา", img_url: `${SACRED_BASE_URL}swpa.jpg` },
  { cardNumber: 61, name: "Knight of Swords", type: "MINOR", upright_Mean: "ความรวดเร็ว, การพุ่งชนเป้าหมาย", reverse_Mean: "ความหุนหันพลันแล่น, การปะทะที่ไร้สติ", img_url: `${SACRED_BASE_URL}swkn.jpg` },
  { cardNumber: 62, name: "Queen of Swords", type: "MINOR", upright_Mean: "ความฉลาด, ความตรงไปตรงมา", reverse_Mean: "ความเย็นชา, การตัดสินด้วยอารมณ์รุนแรง", img_url: `${SACRED_BASE_URL}swqu.jpg` },
  { cardNumber: 63, name: "King of Swords", type: "MINOR", upright_Mean: "อำนาจปัญญา, ความยุติธรรมเด็ดขาด", reverse_Mean: "ความเผด็จการ, การใช้อำนาจกดขี่", img_url: `${SACRED_BASE_URL}swki.jpg` },

  // --- PENTACLES ---
  { cardNumber: 64, name: "Ace of Pentacles", type: "MINOR", upright_Mean: "โอกาสเงินใหม่, ความมั่งคั่งเริ่มต้น", reverse_Mean: "สูญเสียโอกาสเงิน, การใช้จ่ายฟุ่มเฟือย", img_url: `${SACRED_BASE_URL}peac.jpg` },
  { cardNumber: 65, name: "Two of Pentacles", type: "MINOR", upright_Mean: "การปรับสมดุลเงิน, การจัดการงานหลายอย่าง", reverse_Mean: "ความยุ่งเหยิง, การเงินติดขัด, สับรางไม่ทัน", img_url: `${SACRED_BASE_URL}pe02.jpg` },
  { cardNumber: 66, name: "Three of Pentacles", type: "MINOR", upright_Mean: "การทำงานเป็นทีม, ทักษะฝีมือ", reverse_Mean: "งานไม่มีคุณภาพ, การขาดความร่วมมือ", img_url: `${SACRED_BASE_URL}pe03.jpg` },
  { cardNumber: 67, name: "Four of Pentacles", type: "MINOR", upright_Mean: "การประหยัด, ความมั่นคง, ความหวง", reverse_Mean: "ความโลภ, การยึดติดวัตถุมากเกินไป", img_url: `${SACRED_BASE_URL}pe04.jpg` },
  { cardNumber: 68, name: "Five of Pentacles", type: "MINOR", upright_Mean: "ความยากลำบากทางการเงิน, ความอ้างว้าง", reverse_Mean: "การเริ่มฟื้นตัว, ได้รับความช่วยเหลือ", img_url: `${SACRED_BASE_URL}pe05.jpg` },
  { cardNumber: 69, name: "Six of Pentacles", type: "MINOR", upright_Mean: "การแบ่งปัน, ความใจกว้าง, การได้โชค", reverse_Mean: "ความเห็นแก่ตัว, หนี้สิน, การทำทานหวังผล", img_url: `${SACRED_BASE_URL}pe06.jpg` },
  { cardNumber: 70, name: "Seven of Pentacles", type: "MINOR", upright_Mean: "การรอคอยผลกำไร, ความอดทนเพาะปลูก", reverse_Mean: "ความล้มเหลวชั่วคราว, ความท้อถอยในการงาน", img_url: `${SACRED_BASE_URL}pe07.jpg` },
  { cardNumber: 71, name: "Eight of Pentacles", type: "MINOR", upright_Mean: "ความขยัน, การฝึกฝนทักษะให้เชี่ยวชาญ", reverse_Mean: "ความขี้เกียจ, ขาดสมาธิในการทำงาน", img_url: `${SACRED_BASE_URL}pe08.jpg` },
  { cardNumber: 72, name: "Nine of Pentacles", type: "MINOR", upright_Mean: "ความมั่งคั่งด้วยลำแข้งตนเอง, ความสำราญ", reverse_Mean: "ความฟุ่มเฟือยเกินฐานะ, การพึ่งพาคนอื่น", img_url: `${SACRED_BASE_URL}pe09.jpg` },
  { cardNumber: 73, name: "Ten of Pentacles", type: "MINOR", upright_Mean: "มรดก, ความมั่นคงระยะยาวในครอบครัว", reverse_Mean: "ความขัดแย้งเรื่องเงินในบ้าน, ทรัพย์สินมีปัญหา", img_url: `${SACRED_BASE_URL}pe10.jpg` },
  { cardNumber: 74, name: "Page of Pentacles", type: "MINOR", upright_Mean: "โอกาสงานใหม่, การศึกษาหาความรู้", reverse_Mean: "ความล่าช้า, ขาดวิสัยทัศน์, โฟกัสผิดจุด", img_url: `${SACRED_BASE_URL}pepa.jpg` },
  { cardNumber: 75, name: "Knight of Pentacles", type: "MINOR", upright_Mean: "ความอุตสาหะ, การทำงานหนักอย่างซื่อสัตย์", reverse_Mean: "ความเฉื่อยชา, ความคิดแคบ, ความตระหนี่", img_url: `${SACRED_BASE_URL}pekn.jpg` },
  { cardNumber: 76, name: "Queen of Pentacles", type: "MINOR", upright_Mean: "ความเอื้อเฟื้อ, แม่บ้านแม่เรือน, มั่นคง", reverse_Mean: "ความกังวลเงินทองเกินเหตุ, ความโดดเดี่ยว", img_url: `${SACRED_BASE_URL}pequ.jpg` },
  { cardNumber: 77, name: "King of Pentacles", type: "MINOR", upright_Mean: "ความสำเร็จทางการเงินขั้นสูง, ความมั่งคั่ง", reverse_Mean: "ความโลภ, การทุจริตเพื่อเงิน, ความเห็นแก่ตัว", img_url: `${SACRED_BASE_URL}peki.jpg` }
];